export const ALCHEMY_KEY = "Faz2N2pAnV7b1LMWXmEHx16vN3_BudXZ";

export const L2_ALCHEMY_KEY = "LCNPCoXan5scqbRr4KOZK8kofDifu2fz";

export const WALLETCONNECT_PROJECT_ID = "70931f4b1623ccc50c3881f1c1a3162c";

export const CONNECT_KIT_THEME = {
  "--ck-font-family": "PressStart2P",
  "--ck-modal-heading-font-weight": 600,
  "--ck-body-color": "#FFFFFF",
  "--ck-body-font-size": "12px",
  "--ck-body-color-muted": "#FCF5F1",
  "--ck-body-color-muted-hover": "#FCF5F1",
  "--ck-body-color-danger": "#D8392E",
  "--ck-body-color-valid": "#53B484",
  "--ck-overlay-background": "rgba(0, 0, 0, 0.8)",
  "--ck-border-radius": "24px",
  "--ck-body-background": "#08111b",
  "--ck-body-background-transparent": "#08111b",
  "--ck-body-background-secondary": "#142b42",
  "--ck-body-background-secondary-hover-background": "#142b42",
  "--ck-body-background-secondary-hover-outline": "#142b42",
  "--ck-body-background-tertiary": "",
  "--ck-primary-button-color": "#FFFFFF",
  "--ck-primary-button-background": "#08111b",
  "--ck-primary-button-hover-color": "#1d7e8d",
  "--ck-primary-button-hover-background": "#0a121a",
  "--ck-primary-button-active-color": "#FFFFFF",
  "--ck-primary-button-active-background": "#0a121a",
  "--ck-primary-button-border-radius": "24px",
  "--ck-connectbutton-font-size": "12px",
  "--ck-connectbutton-color": "#FFFFFF",
  "--ck-connectbutton-background": "#08111b",
  "--ck-connectbutton-hover-color": "#1d7e8d",
  "--ck-connectbutton-hover-background": "#0a121a",
  "--ck-connectbutton-active-color": "#FFFFFF",
  "--ck-connectbutton-active-background": "#0a121a",
  "--ck-connectbutton-balance-color": "#FFFFFF",
  "--ck-connectbutton-balance-background": "#08111b",
  "--ck-connectbutton-balance-hover-background": "#0a121a",
  "--ck-connectbutton-balance-active-background": "#0a121a",
  "--ck-secondary-button-color": "#FFFFFF",
  "--ck-secondary-button-background": "#08111b",
  "--ck-secondary-button-hover-color": "#1d7e8d",
  "--ck-secondary-button-hover-background": "#0a121a",
  "--ck-secondary-button-active-color": "#FFFFFF",
  "--ck-secondary-button-active-background": "#0a121a",
  "--ck-tertiary-button-color": "#FFFFFF",
  "--ck-tertiary-button-background": "#08111b",
  "--ck-tertiary-button-hover-color": "#1d7e8d",
  "--ck-tertiary-button-hover-background": "#0a121a",
  "--ck-tertiary-button-active-color": "#FFFFFF",
  "--ck-tertiary-button-active-background": "#0a121a",
  "--ck-dropdown-button-color": "#FFFFFF",
  "--ck-dropdown-button-background": "#08111b",
  "--ck-dropdown-button-hover-color": "#1d7e8d",
  "--ck-dropdown-button-hover-background": "#0a121a",
  "--ck-dropdown-button-active-color": "#FFFFFF",
  "--ck-dropdown-button-active-background": "#0a121a",
  "--ck-body-disclaimer-link-color": "#FFFFFF",
  "--ck-body-disclaimer-link-hover-color": "#1d7e8d",
  "--ck-body-disclaimer-color": "#FCF5F1",
  "--ck-qr-dot-color": "#000000",
  "--ck-qr-border-color": "#FFFFFF",
  "--ck-focus-color": "#1d7e8d",
  "--ck-copytoclipboard-stroke": "#FCF5F1",
  "--ck-tooltip-background": "#08111b",
  "--ck-tooltip-background-secondary": "#0a121a",
  "--ck-tooltip-color": "#FFFFFF",
  "--ck-siwe-border": "#FFFFFF",
  "--ck-body-action-color": "#FFFFFF",
  "--ck-body-divider": "#FFFFFF",
};
